# Generated by Django 5.1.5 on 2025-02-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_id', models.CharField(max_length=5)),
                ('itemname', models.CharField(max_length=255)),
                ('itemid', models.BigIntegerField(blank=True, null=True)),
                ('itemqty', models.IntegerField(blank=True, default=0)),
                ('itempurrate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('itemmrp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('itemsalerate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('itembarcode', models.BigIntegerField(blank=True, null=True)),
                ('childbarcode', models.BigIntegerField(blank=True, null=True)),
                ('locid', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
