# Generated by Django 5.1.5 on 2025-02-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastercreations', '0002_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_acc_name', models.CharField(max_length=100)),
                ('bank_acc_num', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=100)),
                ('locid', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastercreations.business')),
            ],
        ),
    ]
